version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo dpkg --add-architecture i386 && sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot wine32 wine64 rpm nasm make
      - run:
          name: Install the SmallerC compiler and generate builds
          command: |
            git clone https://github.com/alexfru/SmallerC.git 
            cd SmallerC
            make
            export PATH=$PATH:$(pwd)
            echo "export PATH=\$PATH:$(pwd)" >> $BASH_ENV
            cd ..
            make QroVMT.bin 
      - run:
          name: Move .bin files to a separate directory
          command: |
            mkdir -p bin_artifacts
            find . -type f -name '*.bin' -exec mv {} bin_artifacts/ \;

      - store_artifacts:
          path: ~/repo/bin_artifacts