version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo dpkg --add-architecture i386 && sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot wine32 wine64 rpm nasm make
            sudo chmod -R +x *
      - run:
          name: Generate Builds
          command: |
            cd smallerc
            export PATH=$PATH:$(pwd)
            cd ..
            make QroVMT.bin 

      - store_artifacts:
          path: ~/repo/