version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.17.4
    steps:
      - checkout
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo dpkg --add-architecture i386 && sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot wine32 wine64 rpm nasm make
            sudo chmod -R +x *
      - run:
          name: Add SmallerC to PATH
          path: ~/repo/smallerc
          command: echo 'export PATH=$PATH:$(pwd)' >> $BASH_ENV
      - run:
          name: Generate Builds
          command: make QroVMT.bin 

      - store_artifacts:
          path: ~/repo/